

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.9
startup_mode = "FullScreen"

[window.padding]
x = 25
y = 20

[font]

size = 16

[font.normal]
family = "TempleOS"
